export const bookData = [
  {
    category: "shortStories",
    length: "short story",
    title: "Soul Bound",
    subtitle: "Prequel to the Kat Drummond Series",
    ebook: "https://books2read.com/u/3yQYyL",
    description: "Even in this world of magic and monsters, moving out shouldn’t be too hard, right? With help from the ghost in my head, I hunt monsters to pay the bills and pay my way through university. Now it’s time I finally get my own place. Through lopping off zombie and giant rat heads, I should have enough money, right?  But if there’s anything consistent about living in Hope City, things are seldom easy. My name is Kat Drummond, and I’m a part- time monster hunter.",
    image: 1,
  },
  {
    category: "KD",
    length: "novel",
    title: "Part-Time Monster Hunter",
    subtitle: "Book one",
    ebook: "https://books2read.com/u/4DPBqk",
    boxset: "https://books2read.com/u/4DD2kd",
    audio: "https://nicholaswoodesmith.gumroad.com/l/ptmh",
    description: "Kat hits it big when a run in with a hostile ghost leads to her entering the big leagues of monster hunting. But does she really have what it takes to face the biggest horrors that Hope City has to offer? This is the best place to start your journey in the Katverse, introducing Kat, her friends and Hope City in all its horrific splendour.",
    image: 2,

  },
  {
    category: "KD",
    length: "novel",
    title: "Blood Cartel",
    subtitle: "Book two",
    ebook: "https://books2read.com/u/mZQvEJ",
    boxset: "https://books2read.com/u/4DD2kd",
    audio: "https://nicholaswoodesmith.gumroad.com/l/blood-cartel",
    description: "As the dust settles after Kat Drummond slays the necromancer and saves the day, she is arrested for murder. Even after being cleared of such a ludicrous crime, Kat is still left in the doghouse and needs to earn back her reputation. But nothing is ever simple in Hope City, and Kat soon finds out that much more is at stake than her reputation.",
    image: 3,
  },
  {
    category: "KD",
    length: "novel",
    title: "Devil’s Gambit",
    subtitle: "Book three",
    ebook: "https://books2read.com/u/3kPlYK",
    boxset: "https://books2read.com/u/4DD2kd",
    audio: "https://nicholaswoodesmith.gumroad.com/l/devils-gambit",
    description: " Titan Mages are going missing. The fact that these mysterious magic-users keep the city from being turned into dust is not lost on Kat as she is given the job of finding out what happened to them. But this investigation will prove to be Kat’s biggest challenge yet, as she uncovers not only the truth about her city, but herself.",
    image: 4,
  },
  {
    category: "shortStories",
    length: "short story",
    title: "The Spectral Express",
    subtitle: "A katverse short story",
    ebook: "https://books2read.com/u/bzKdZq",
    description: "Kat and Treth are tasked to investigate a train that has been disturbing the locals of a usually quiet suburb of Hope City. Odd thing is: there hasn’t been a train running in Hope City for over thirty years. But that won’t stop Kat from slaying some monsters and earning her pay.",
    image: 5,
  },
  {
    category: "KD",
    length: "novel",
    title: "Necrolord",
    subtitle: "Book four",
    ebook: ": https://books2read.com/u/bM7vx5",
    boxset: "https://books2read.com/u/4DD2kd",
    description: "A necromancer lord has risen in the slums of Hope City, and Kat has been tasked by the Council itself to put a stop to this dark warlord. But as the body count rises, allies perish, and Kat’s most powerful enemy yet runs circles around her – is there hope left for Hope City?",
    image: 6,
  },
  {
    category: "KD",
    length: "novel",
    title: "Darkness Beckons",
    subtitle: "Book five",
    ebook: "https://books2read.com/u/mV8vAp",
    boxset: "https://books2read.com/u/49LZw0",
    description: "Kat has been captured by her mortal enemy, the Necrolord. Imprisoned in darkness, Kat will need to resist temptation, and face the truth of her world and her past. But is she powerful enough to resist the temptations of the darkness? And can her friends find her in time?",
    image: 7,
  },
  {
    category: "KD",
    length: "novel",
    title: "Lost Huntress",
    subtitle: "Book six",
    ebook: "https://books2read.com/u/mV8vAp",
    boxset: "https://books2read.com/u/49LZw0",
    description: "Now free, Kat is feeling lost. This isn’t helped by the fact that her license has been revoked. The events surrounding the Necrolord has not made Kat any new friends, and now she must find a new way to keep the hunt alive. Even if that may require some divine intervention.",
    image: 8,
  },
  {
    category: "KD",
    length: "novel",
    title: "Dead World",
    subtitle: "Book seven",
    ebook: "https://books2read.com/u/boye6Z",
    boxset: "https://books2read.com/u/49LZw0",
    description: "This isn’t Hope City. Kat and Treth have been teleported to another world. A dead world, ravaged by the undead. Can they ever return home? And what is this mysterious world?",
    image: 9,
  },
  {
    category: "KD",
    length: "novel",
    title: "Silver Brotherhood",
    subtitle: "Book eight",
    ebook: "https://books2read.com/u/md1EKW",
    boxset: "https://books2read.com/u/49LZw0",
    description: "As Kat returns to Earth, a friend returns to Kat. But she’s in trouble. Fortunately, Kat is no stranger to trouble. But this is Hope City, and trouble comes not in twos or threes, but tidal waves. Old mentors become enemies, and monsters become allies as Kat learns that the world isn’t black or white. Often, it’s silver.",
    image: 10,
  },
  {
    category: "KD",
    length: "novel",
    title: "The Fae Hunt",
    subtitle: "Book nine",
    ebook: "https://books2read.com/u/3nX1eK",
    boxset: "https://books2read.com/u/38ez0Z",
    description: "A plague has fallen on Hope City. And Kat may be the only one who can stop it. But to do so, she will need every bit of power, skill and alliance that she has built over her career. And even then, it may not be enough. But that won’t stop Kat. When there is one last light left, there is hope.",
    image: 11,
  },
  {
    category: "shortStories",
    length: "short story",
    title: "A Hope City Halloween",
    subtitle: "A Katverse Halloween Special",
    ebook: "https://books2read.com/u/3GWLMQ",
    description: "What is the spirit of Halloween? Kara Del’tara, an elf child living in the slums of Hope City, doesn’t rightfully know. But she wants to find out. Accompanied by her friends, Kara will delve into the spooky heart of Hope City to discover the secrets behind the spookiest of human holidays. Or die of fright trying.",
    image: 12,
  },
  {
    category: "KD",
    length: "novel",
    title: "Blood Hunter",
    subtitle: "A Katverse Novel",
    ebook: "https://books2read.com/u/bzV2pq",
    boxset: "https://books2read.com/u/38ez0Z",
    description: "Vampires took everything from Guy Mgebe. And now, he will have his revenge. But to take revenge upon the Children of Blood is not easy. Guy will need to become more than human. More than a  warrior. He must become a Blood Hunter, and dedicate his life to hunting the vampires who took his life from him.",
    image: 13,
  },
  {
    category: "KD",
    length: "novel",
    title: "Dark Order",
    subtitle: "Book ten",
    ebook: "https://books2read.com/u/bzV2pj",
    boxset: "https://books2read.com/u/bzV2pj",
    description: "Kat can’t trust anyone, as a new villain targets her and her friends in a life or death chess match that embroils the city and threatens everything Kat has saved and built. But with new allies, new fame, and new powers, Kat is ready to face a new dark order – and resist its domination.",
    image: 14,
  },
  {
    category: "KD",
    length: "novel",
    title: "The Silver Star",
    subtitle: "Book eleven",
    ebook: "https://books2read.com/u/mg1wKz",
    boxset: "https://books2read.com/u/38ez0Z",
    description: "Kat’s aunt, long thought dead, is alive! But she is trapped across the sea in the soon to be war-torn lands of New Sintar – an elvish kingdom built over the ashes of New Zealand. Kat has never faced war before. Not truly. But her aunt is all she has left of her family. And she will save her.",
    image: 15,
  },
  {
    category: "shortStories",
    length: "short story",
    title: "The Pixie’s Power",
    subtitle: "A Duer Short Story",
    ebook: "https://books2read.com/u/b5jDO6",
    description: "While Kat is in New Sintar, Duer and his newfound kinth are faced with demons from the past. Figuratively and literally. But in adversity, these little pixies will find strength. And most importantly, each other.",
    image: 16,

  },
  {
    category: "KD",
    length: "novel",
    title: "Cursed Earth",
    subtitle: "Book twelve",
    ebook: "https://books2read.com/u/bP7G1x",
    boxset: "https://books2read.com/u/4960Rp",
    description: "A new darkness has descended on Hope City, naming itself after an old one. This comes as a magical script essential to Hope City’s safety has gone missing. With villains on all sides, Kat has to utilise all of her power to defeat this purest of evil. There is no redemption to be had here. Only carnage.",
    image: 17,
  },
  {
    category: "KD",
    length: "novel",
    title: "Children of Blood",
    subtitle: "Book thirteen",
    ebook: "https://books2read.com/u/4Avogp",
    boxset: "https://books2read.com/u/4960Rp",
    description: "The Izingane Zegazi, the Children of Blood, have finally caught up to Guy Mgebe. And they are coming with a vengeance. But Guy has new allies now. Kat Drummond and the Crusaders will hold the line again vampire, monster, or beast. Even if it means finding new allies in dark places.",
    image: 18,
  },
  {
    category: "KD",
    length: "novel",
    title: "The Last Light",
    subtitle: "Book fourteen",
    ebook: "https://books2read.com/u/m2d2Xd",
    boxset: "https://books2read.com/u/4960Rp",
    description: "The most dangerous man in the world is coming to Hope City. The man who killed Kat’s parents and turned Candace Evergreen into the Necrolord. And he will stop at nothing to ensure his sick plans come to fruition. Even if it means inviting the apocalypseto Hope City.",
    image: 19,
  },
  {
    category: "KD",
    length: "novel",
    title: "Werewolves & Wizardry",
    subtitle: "A Katverse Novel",
    ebook: "https://books2read.com/u/mg1wKD",
    boxset: "https://books2read.com/u/4960Rp",
    description: "After the Mentor’s onslaught and almost apocalypse, Trudie and Pranish must pick up the pieces as Kat leaves Hope City. But Trudie’s pack has grown, including many ex-rogue werewolves in her ranks who she must tame or discipline to maintain the safety of her family. As she does so, Pranish discovers a threat to his estranged family, and must decide what matters more: his old family, or new pack?",
    image: 20,
  },
  {
    category: "KD",
    length: "novel",
    title: "Shadow Realm",
    subtitle: "Book fifteen",
    ebook: "https://books2read.com/u/47gwkR",
    description: "Kat doesn’t want to fight a war, but if it means ending the threat of the Conclave once and for all, she will follow Thor into the bowels of Europe and fight the most brutal war on the continent since the Cataclysm. But first, she must get there, and travel through darkness and shadows that she has never faced before – putting her truly to the test as not just the bearer of the Vessel, but as the Last Light.",
    image: 21,
  },
  {
    category: "KD",
    length: "novel",
    title: "The Titan Awakes",
    subtitle: "Book sixteen",
    ebook: "https://books2read.com/u/bOPWwJ",
    description: "Kat, Treth, Brett and Candace return to a Hope City on the eve of invasion. Exhausted by the war in Europe, none of them want to fight another one. But what choice do they have with their home threatened with annihilation? But, the true threat to Hope City may not be the invaders at the gates – but the very titan resting so fitfully at its heart.",
    image: 22,
  },
  {
    category: "shortStories",
    length: "short story",
    title: "Demonic Departure",
    subtitle: "A Hammond York Short Story",
    ebook: "https://books2read.com/u/4EJj2M",
    description: "Hammond York is the best damn pyromancer in Hope City. Not that it would show lately. Ever since losing his cat in a brutal divorce, he’s lost his edge. But now, he’s dedicated to getting it back – alongside his cat. Problem is, while his ex-wife has his cat and his house, he can’t even remember marrying her.",
    image: 23,
  },
  {
    category: "CG",
    length: "novel",
    title: "Pure Power",
    subtitle: "Book One",
    ebook: "https://books2read.com/u/m0WAVJ",
    description: "Cindy Giles, a talented magical healer, must dive into the brutal world of demon slaying and monster hunting after a series of demon attacks causes her to doubt if she’s really making a difference. She joins an ensemble of roguish monster hunters, led by the fiery Tom McLoughren.",
    image: 24,
  },
  {
    category: "CG",
    length: "novel",
    title: "Pure Protector",
    subtitle: "Book Two",
    ebook: "https://books2read.com/u/mvBdYX",
    description: "Cindy Giles must put her investigative skills to the test as her friend is framed for murder. But while she plays detective, a bigger conspiracy is brewing in the bowels of Hope city.",
    image: 25,
  },
  {
    category: "CG",
    length: "novel",
    title: "Pure Prophecy",
    subtitle: "Book Three",
    ebook: "https://books2read.com/u/3kBqXL",
    description: "Cindy Giles still hasn’t recovered from events seven years prior, but time waits for no one as she is once again thrust into the role of demon slayer and detective, after an infernal prophecy promises to plunge the world into darkness.",
    image: 26,
  },
]

export default bookData;